# Generated by Django 3.1.7 on 2021-03-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_prod', models.IntegerField(max_length=100)),
                ('code_article', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('heure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='production_NC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_prod_NC', models.IntegerField(max_length=100)),
                ('code_article', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('heure', models.CharField(max_length=100)),
            ],
        ),
    ]
