# Generated by Django 3.1.7 on 2021-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EF_PPM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_per', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('heure', models.CharField(max_length=100)),
                ('EFF_h', models.CharField(max_length=100)),
                ('PPM_h', models.CharField(max_length=100)),
                ('EFF_j', models.CharField(max_length=100)),
                ('PPM_j', models.CharField(max_length=100)),
            ],
        ),
    ]
