# Generated by Django 3.1.7 on 2021-03-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EF_PPM', '0004_auto_20210318_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='heure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='heure',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='production_nc',
            name='heure',
            field=models.TimeField(),
        ),
    ]
