# Generated by Django 3.1.7 on 2021-03-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EF_PPM', '0005_auto_20210322_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='EFF_h',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='EFF_j',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='PPM_h',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='PPM_j',
            field=models.FloatField(),
        ),
    ]
