# Generated by Django 3.1.7 on 2021-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EF_PPM', '0006_auto_20210323_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='id',
        ),
        migrations.AlterField(
            model_name='kpi',
            name='EFF_h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='EFF_j',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='ID_per',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='PPM_h',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='PPM_j',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='heure',
            field=models.TimeField(null=True),
        ),
    ]
